apps/webapp/web/router.ex
defmodule Webapp.Router do
  use Webapp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Webapp.Authentication, repo: Webapp.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Webapp do
    pipe_through :browser # Use the default browser stack

    get     "/about", PageController, :about
    get     "/login", PageController, :login
    get     "/", PageController, :index
  end

  scope "/profile", Webapp do
    pipe_through [:browser, :authenticate_user]

    patch   "/", ProfileController, :update
    put     "/", ProfileController, :update
    get     "/", ProfileController, :index
  end

  #Authentication scope
  scope "/auth", Webapp do
    pipe_through :browser

    get     "/:provider", AuthController, :request
    get     "/:provider/callback", AuthController, :callback
    post    "/:provider/callback", AuthController, :callback
    delete  "/logout", AuthController, :delete
  end

  scope "/admin", Webapp do
    pipe_through [:browser, :authenticate_user, :is_admin]


  end

  #Other scopes may use custom stacks.
  scope "/api", Webapp do
    pipe_through [:api]
    #Public API
    scope "/top" do
      get "/contestants", ContestantController, :top
      get "/teams/", TeamController, :top
      get "/battles/", BattleController, :top
    end

    scope "/bottom" do
      get "/contestants/", ContestantController, :botom
      get "/teams/", TeamController, :bottom
      get "/battles/", BattleController, :bottom
    end

    scope "/contestants" do
      get     "/page/:page", ContestantController, :page
      get     "/:id", ContestantController, :show
      get     "/", ContestantController, :index
    end

    scope "/battles" do
      get     "/page/:page", BattleController, :page
      get     "/:id", BattleController, :show
      get     "/", BattleController, :index
    end

    scope "/teams" do
      get     "/page/:page", TeamController, :page
      get     "/:id", TeamController, :show
      get     "/", TeamController, :index
    end

    scope "/search" do
      post "/contestants", SearchController, :contestants
      post "/teams", SearchController, :teams
      post "/battles", SearchController, :battles
      post "/", SearchController, :all
    end

    #Private Api
    pipe_through [:authenticate_api_user]

    scope "/contestants" do
      post    "/create", ContestantController, :create

      patch   "/:id", ContestantController, [:update, :authenticate_api_user]

      put     "/:id", ContestantController, [:update, :authenticate_api_user]

      #delete  "/:id", ContestantController, [:delete, :authenticate_api_user]
    end

    scope "/battles" do
      post    "/create", BattleController, :create
      patch   "/:id", BattleController, :update
      put     "/:id", BattleController, :update
      post "/exists", BattleController, :exists

      #delete  "/:id", ContestantController, [:delete, :authenticate_api_user]
    end

    scope "/vote" do
       post "/battles", VoteController, :battle
       post "/contestants", VoteController, :contestant
       post "/teams", VoteController, :team      
    end

    scope "/teams" do
      post "/create", TeamController, :create
      post "/similar", TeamController, :similar_teams
    end
    resources "/participants", ParticipantController, except: [:new, :edit]
    resources "/votes", VoteController, except: [:new, :edit]
  end
end

apps/webapp/web/views/layout_view.ex
defmodule Webapp.LayoutView do
  use Webapp.Web, :view
end

apps/webapp/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ERB Voting!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body id="app">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a v-link="{ path: '/' }" class="navbar-brand">ERB Voting</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li v-link="{ path: '/battles' }" class="btn">
                    <a>The Battles</a>
                </li>
                <li v-link="{ path: '/contestants'}" class="btn">
                    <a >The Contestants</a>
                </li>
                <li v-link="{ path: '/teams' }" class="btn">
                    <a>The Teams</a>
                </li>
                <li v-link="{ path: '/about' }" class="btn">
                    <a>About</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <%= if @current_user do %>
                <h5> Welcome, <%= link @current_user.name, to: profile_path(@conn, :index) %>!
                    <!-- <img src="<%= @current_user.image %>" class="img-circle"/>-->
                    <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-sm btn-danger"
                    %></h5>
                <% else %>
                <li>
                    <a v-link="{ path: '/login' }">Log In / Register</a>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
    <div class="container-fluid">
        <p class="alert alert-info alert-dismissible" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger alert-dismissible" role="alert"><%= get_flash(@conn, :error) %></p>

        <main role="main">
            <router-view
                    keep-alive>
            </router-view>
        </main>
    </div > <!-- /container -->
<script>window.userToken = "<%= assigns[:user_token] %>"</script>
<script>window.apiToken = "<%= assigns[:api_token] %>"</script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script src="<%= static_path(@conn, "/js/vue.js") %>"></script>
<script src="<%= static_path(@conn, "/js/vue-resource.js") %>"></script>
<script src="<%= static_path(@conn, "/js/vue-router.js") %>"></script>
<script src="<%= static_path(@conn, "/js/bootstrap.min.js") %>"></script>
<script src="<%= static_path(@conn, "/js/build.js") %>"></script>

    </body >
</html >